# Generated by Django 5.2.17 on 2026-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebedouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
