# Generated by Django 5.2.17 on 2026-09-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0002_coleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fora_de_operacao', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('cloro', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('condutividade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('nitrato', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('turbidez_valor', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('turbidez_abaixo_limite', models.BooleanField(default=False)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coliformes_totais', models.CharField(blank=True, choices=[('', '—'), ('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente')], default='', max_length=10)),
                ('ecoli', models.CharField(blank=True, choices=[('', '—'), ('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente')], default='', max_length=10)),
                ('filtro', models.CharField(blank=True, choices=[('', '—'), ('dentro', 'Dentro da validade'), ('vencido', 'Vencido')], default='', max_length=10)),
                ('bebedouro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='bebedouros.bebedouro')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='bebedouros.coleta')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('coleta', 'bebedouro'), name='uniq_resultado_por_bebedouro_na_coleta')],
            },
        ),
    ]
