# Generated by Django 5.2.17 on 2026-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0003_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebedouro',
            name='ativo',
        ),
        migrations.AddField(
            model_name='bebedouro',
            name='desativado_em',
            field=models.DateField(blank=True, null=True, verbose_name='Desativado em'),
        ),
    ]
