# Generated by Django 5.2.17 on 2026-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0004_remove_bebedouro_ativo_bebedouro_desativado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='iqab',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='iqab_classificacao',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='resultado',
            name='iqab_co',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='iqab_qfq',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='iqab_qm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='iqab_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='resultado',
            name='metodologia_versao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
