# Generated by Django 5.2.17 on 2026-09-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0005_resultado_iqab_resultado_iqab_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='iqab',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='iqab_co',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='iqab_qfq',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='iqab_qm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
