# Generated by Django 5.2.17 on 2026-09-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0006_alter_resultado_iqab_alter_resultado_iqab_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='publicada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
