# Generated by Django 5.2.17 on 2026-09-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0007_coleta_publicada_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_troca', models.DateField(verbose_name='Troca realizada em')),
                ('bebedouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_filtro', to='bebedouros.bebedouro')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_filtro', to='bebedouros.coleta')),
            ],
            options={
                'ordering': ['-data_troca'],
                'constraints': [models.UniqueConstraint(fields=('coleta', 'bebedouro'), name='uniq_troca_filtro_por_bebedouro_na_coleta')],
            },
        ),
    ]
