# Generated by Django 5.2.17 on 2026-09-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebedouros', '0008_trocafiltro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebedouro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bebedouros/fotos/', verbose_name='Foto'),
        ),
    ]
